---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
    - name: centos7 - start the container
      command: lxc-attach wails-centos
      ignore_errors: True
      register: hello

    - debug: msg="{{ hello.stdout }}"

    - debug: msg="{{ hello.stderr }}"

    - name: centos7 - ls
      shell: ls
      ignore_errors: True
      register: hello

    - debug: msg="{{ hello.stdout }}"

    - debug: msg="{{ hello.stderr }}"